[env]
TERM = "xterm-256color"

[font]
size = 18

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "Full"

[window.padding]
x = 7
y = 0

[general]
# theme from catpuccin https://github.com/catppuccin/alacritty
import = ["~/.conFig/alacritty/themes/themes/dracula_plus.toml"]

[terminal]
